GET http://localhost:8000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJSYW56RGV2QGRldi5jb20iLCJpYXQiOjE3MzQzNTcxNTIsImV4cCI6MTczNDM1NzE2N30.UvYNP0oFgp3xYn4cdcigKovOzTEnXz6ge0ELWLW9veQ

###
POST http://localhost:8000/register
Content-Type: application/json

{
    "name": "RanzDev",
    "email": "RanzDev@dev.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "RanzDev@dev.com",
    "password": "123456"
}

###
POST http://localhost:8000/test
Content-Type: application/json

{
    "name": "Ranzdev",
    "email": "ranz@dev.com",
    "password": "1234567",
    "confirmPassword": "123456"
}

